---
<<<<<<< HEAD
services: docker

env:
  - distro: centos7
    redis_daemon: redis
  # - distro: fedora24
  #   redis_daemon: redis
  - distro: ubuntu1604
    redis_daemon: redis-server

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Redis is running, and can be stopped and started cleanly.
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl --no-pager status ${redis_daemon}'
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl --no-pager stop ${redis_daemon}'
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl --no-pager start ${redis_daemon}'

after_failure:
  - 'docker exec --tty ${container_id} env TERM=xterm cat /var/log/redis/redis-server.log'
=======
sudo: required

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    redis_daemon: redis
  # - distro: fedora24
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   redis_daemon: redis
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    redis_daemon: redis-server

services:
  - docker

before_install:
  # Pull container.
  - 'sudo docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Make sure Redis is running, and can be stopped and started cleanly.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager status ${redis_daemon}'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager stop ${redis_daemon}'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager start ${redis_daemon}'

after_failure:
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/redis/redis-server.log'

after_success:
  # Clean up.
  - 'sudo docker stop "$(cat ${container_id})"'
>>>>>>> dd747fad95dbf3b776a00731ba9641b7f5e76343

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
