---
- name: Set the PHP webserver daemon correctly when nginx is in use.
  set_fact:
    php_webserver_daemon: nginx
  when: drupalvm_webserver == 'nginx'
  tags: ['webserver', 'database', 'php']

- name: Set the correct XHProf package when PHP 5.6 is used.
  set_fact:
    xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
    xhprof_download_folder_name: xhprof-master
  when: php_version == '5.6'

- name: Ensure PHP version -specific workspace directory exists.
  file:
    path: "/root/php{{ php_version }}"
    state: directory
    mode: 0775
  tags: ['php']
